# Scanner Configuration - User Adjustable Parameters
# Generated by Human-in-the-Loop Formatter
class ScannerConfig:
    """User-configurable scanner parameters"""
    high_pct_chg_tier1 = 0.3
    high_pct_chg_tier2 = 0.2
    high_pct_chg_tier3 = 0.1
    high_pct_chg_tier4 = 0.07
    high_pct_chg_tier5 = 0.05
    c_ua_tier1_min = 5
    c_ua_tier1_max = 15
    c_ua_tier2_min = 15
    c_ua_tier2_max = 25
    c_ua_tier3_min = 25
    c_ua_tier3_max = 50
    c_ua_tier4_min = 50
    c_ua_tier4_max = 90
    c_ua_tier5_min = 90
    h_dist_tier1 = 2.5
    h_dist_tier2 = 2.0
    h_dist_tier3 = 1.5
    h_dist_tier4 = 1.0
    h_dist_tier5 = 0.75
    high_chg_atr1_min = 0.7
    high_chg_atr_min = 1.0
    dist_h_9ema_atr1_min = 1.5
    dist_h_20ema_atr1_min = 2.0
    dist_h_9ema_atr_min = 1.5
    dist_h_20ema_atr_min = 2.0
    volume_min = 10000000
    dollar_volume_min = 500000000
    volume1_min = 10000000
    dollar_volume1_min = 100000000
    c_ua_min = 5
    h_dist_highest_high_20_atr = 2.5

# Initialize configuration
config = ScannerConfig()

# Momentum D3 Extended Pattern Scanner
# D3 Extended Momentum Pattern - Multi-day validation with strict criteria
# LC Pattern: momentum_d3_extended_pattern

import pandas as pd, numpy as np, requests
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

# ───────── config ─────────
session  = requests.Session()
API_KEY  = "Fm7brz4s23eSocDErnL68cE7wspz2K1I"
BASE_URL = "https://api.polygon.io"
MAX_WORKERS = 6

PRINT_FROM = "2025-01-01"  # set None to keep all
PRINT_TO   = None

# ───────── knobs ─────────
P = {
    # Pattern-specific parameters
    "high_pct_chg_tier1": 0.3,
    "high_pct_chg_tier2": 0.2,
    "high_pct_chg_tier3": 0.1,
    "high_pct_chg_tier4": 0.07,
    "high_pct_chg_tier5": 0.05,
    "c_ua_tier1_min": 5,
    "c_ua_tier1_max": 15,
    "c_ua_tier2_min": 15,
    "c_ua_tier2_max": 25,
    "c_ua_tier3_min": 25,
    "c_ua_tier3_max": 50,
    "c_ua_tier4_min": 50,
    "c_ua_tier4_max": 90,
    "c_ua_tier5_min": 90,
    "h_dist_tier1": 2.5,
    "h_dist_tier2": 2.0,
    "h_dist_tier3": 1.5,
    "h_dist_tier4": 1.0,
    "h_dist_tier5": 0.75,
    "high_chg_atr1_min": 0.7,
    "high_chg_atr_min": 1.0,
    "dist_h_9ema_atr1_min": 1.5,
    "dist_h_20ema_atr1_min": 2.0,
    "dist_h_9ema_atr_min": 1.5,
    "dist_h_20ema_atr_min": 2.0,
    "volume_min": 10000000,
    "dollar_volume_min": 500000000,
    "volume1_min": 10000000,
    "dollar_volume1_min": 100000000,
    "c_ua_min": 5,
    "h_dist_highest_high_20_atr": 2.5,
}

# ───────── universe ─────────
SYMBOLS = [
    'MSTR','SMCI','DJT','BABA','TCOM','AMC','SOXL','MRVL','TGT','DOCU','ZM','DIS',
    'NFLX','SNAP','RBLX','META','SE','NVDA','AAPL','MSFT','GOOGL','AMZN','TSLA',
    'AMD','INTC','BA','PYPL','QCOM','ORCL','KO','PEP','ABBV','JNJ','CRM','BAC',
    'JPM','WMT','CVX','XOM','COP','RTX','SPGI','GS','HD','LOW','COST','UNH','NKE',
    'LMT','HON','CAT','LIN','ADBE','AVGO','TXN','ACN','UPS','BLK','PM','ELV','VRTX',
    'ZTS','NOW','ISRG','PLD','MS','MDT','WM','GE','IBM','BKNG','FDX','ADP','EQIX',
    'DHR','SNPS','REGN','SYK','TMO','CVS','INTU','SCHW','CI','APD','SO','MMC','ICE',
    'FIS','ADI','CSX','LRCX','GILD','RIVN','PLTR','SNOW','SPY','QQQ','IWM','RIOT',
    'MARA','COIN','MRNA','CELH','UPST','AFRM','DKNG'
]

# ───────── fetch ─────────
def fetch_daily(tkr: str, start: str, end: str) -> pd.DataFrame:
    url = f"{BASE_URL}/v2/aggs/ticker/{tkr}/range/1/day/{start}/{end}"
    r   = session.get(url, params={"apiKey": API_KEY, "adjusted":"true", "sort":"asc", "limit":50000})
    r.raise_for_status()
    rows = r.json().get("results", [])
    if not rows: return pd.DataFrame()
    return (pd.DataFrame(rows)
            .assign(Date=lambda d: pd.to_datetime(d["t"], unit="ms", utc=True))
            .rename(columns={"o":"Open","h":"High","l":"Low","c":"Close","v":"Volume"})
            .set_index("Date")[["Open","High","Low","Close","Volume"]]
            .sort_index())

# ───────── metrics ─────────
def add_daily_metrics(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty: return df
    m = df.copy()
    try: m.index = m.index.tz_localize(None)
    except Exception: pass

    # Technical indicators
    m["EMA_9"]  = m["Close"].ewm(span=9 , adjust=False).mean()
    m["EMA_20"] = m["Close"].ewm(span=20, adjust=False).mean()
    m["EMA_50"] = m["Close"].ewm(span=50, adjust=False).mean()

    # ATR calculation
    hi_lo   = m["High"] - m["Low"]
    hi_prev = (m["High"] - m["Close"].shift(1)).abs()
    lo_prev = (m["Low"]  - m["Close"].shift(1)).abs()
    m["TR"]      = pd.concat([hi_lo, hi_prev, lo_prev], axis=1).max(axis=1)
    m["ATR_raw"] = m["TR"].rolling(14, min_periods=14).mean()
    m["ATR"]     = m["ATR_raw"].shift(1)

    # Volume metrics
    m["VOL_AVG"]     = m["Volume"].rolling(14, min_periods=14).mean().shift(1)
    m["ADV20_$"]     = (m["Close"] * m["Volume"]).rolling(20, min_periods=20).mean().shift(1)

    # Price metrics
    m["High_pct_chg"] = (m["High"] - m["Close"].shift(1)) / m["Close"].shift(1) * 100
    m["High_pct_chg1"] = m["High_pct_chg"].shift(1)

    # Additional LC metrics
    m["Close_ua"] = m["Close"]  # Price under analysis
    m["High_chg_atr"] = (m["High"] - m["Close"].shift(1)) / m["ATR"]
    m["High_chg_atr1"] = m["High_chg_atr"].shift(1)

    # Distance metrics
    m["Dist_h_9ema_atr"] = (m["High"] - m["EMA_9"]) / m["ATR"]
    m["Dist_h_20ema_atr"] = (m["High"] - m["EMA_20"]) / m["ATR"]
    m["Dist_h_9ema_atr1"] = m["Dist_h_9ema_atr"].shift(1)
    m["Dist_h_20ema_atr1"] = m["Dist_h_20ema_atr"].shift(1)

    # High/Low tracking
    m["Highest_high_20"] = m["High"].rolling(20).max()
    m["Lowest_low_20"] = m["Low"].rolling(20).min()
    m["H_dist_to_lowest_low_20_pct"] = (m["High"] - m["Lowest_low_20"]) / m["Lowest_low_20"] * 100
    m["H_dist_to_highest_high_20_atr"] = (m["High"] - m["Highest_high_20"]) / m["ATR"]

    # Shift columns for previous day analysis
    m["Prev_Close"] = m["Close"].shift(1)
    m["Prev_High"] = m["High"].shift(1)
    m["Prev_Low"] = m["Low"].shift(1)

    return m

# ───────── pattern logic ─────────
def check_pattern(row: pd.Series) -> bool:
    """Check if row matches momentum_d3_extended_pattern pattern"""
    try:
        # Multi-tier high percentage change validation
        c_ua = row.get("Close_ua", row.get("Close", 0))
        high_pct_chg = row.get("High_pct_chg", 0)
        high_pct_chg1 = row.get("High_pct_chg1", 0)
        h_dist_pct = row.get("H_dist_to_lowest_low_20_pct", 0)

        # Tier-based validation
        tier_valid = (
            (high_pct_chg1 >= P["high_pct_chg_tier1"] and high_pct_chg >= P["high_pct_chg_tier1"] and
             c_ua >= P["c_ua_tier1_min"] and c_ua < P["c_ua_tier1_max"] and h_dist_pct >= P["h_dist_tier1"]) or
            (high_pct_chg1 >= P["high_pct_chg_tier2"] and high_pct_chg >= P["high_pct_chg_tier2"] and
             c_ua >= P["c_ua_tier2_min"] and c_ua < P["c_ua_tier2_max"] and h_dist_pct >= P["h_dist_tier2"]) or
            (high_pct_chg1 >= P["high_pct_chg_tier3"] and high_pct_chg >= P["high_pct_chg_tier3"] and
             c_ua >= P["c_ua_tier3_min"] and c_ua < P["c_ua_tier3_max"] and h_dist_pct >= P["h_dist_tier3"]) or
            (high_pct_chg1 >= P["high_pct_chg_tier4"] and high_pct_chg >= P["high_pct_chg_tier4"] and
             c_ua >= P["c_ua_tier4_min"] and c_ua < P["c_ua_tier4_max"] and h_dist_pct >= P["h_dist_tier4"]) or
            (high_pct_chg1 >= P["high_pct_chg_tier5"] and high_pct_chg >= P["high_pct_chg_tier5"] and
             c_ua >= P["c_ua_tier5_min"] and h_dist_pct >= P["h_dist_tier5"])
        )

        # ATR and distance validations
        atr_valid = (
            row.get("High_chg_atr1", 0) >= P["high_chg_atr1_min"] and
            row.get("High_chg_atr", 0) >= P["high_chg_atr_min"] and
            row.get("Dist_h_9ema_atr1", 0) >= P["dist_h_9ema_atr1_min"] and
            row.get("Dist_h_20ema_atr1", 0) >= P["dist_h_20ema_atr1_min"] and
            row.get("Dist_h_9ema_atr", 0) >= P["dist_h_9ema_atr_min"] and
            row.get("Dist_h_20ema_atr", 0) >= P["dist_h_20ema_atr_min"]
        )

        # Volume validations
        volume_valid = (
            row.get("Volume", 0) >= P["volume_min"] and
            row.get("ADV20_$", 0) >= P["dollar_volume_min"] and
            c_ua >= P["c_ua_min"]
        )

        # Higher highs and EMA trend
        trend_valid = (
            row.get("High", 0) >= row.get("Highest_high_20", 0) and
            row.get("EMA_9", 0) >= row.get("EMA_20", 0) and
            row.get("EMA_20", 0) >= row.get("EMA_50", 0)
        )

        return tier_valid and atr_valid and volume_valid and trend_valid
    except Exception:
        return False

# ───────── scan one symbol ─────────
def scan_symbol(sym: str, start: str, end: str) -> pd.DataFrame:
    df = fetch_daily(sym, start, end)
    if df.empty: return pd.DataFrame()
    m  = add_daily_metrics(df)

    rows = []
    for i in range(2, len(m)):
        row = m.iloc[i]
        if check_pattern(row):
            rows.append({
                "Ticker": sym,
                "Date": row.name.strftime("%Y-%m-%d"),
                "Pattern": "momentum_d3_extended_pattern",
                "Close": round(float(row["Close"]), 2),
                "Volume": int(row["Volume"]) if pd.notna(row["Volume"]) else 0,
                "High_pct_chg": round(float(row.get("High_pct_chg", 0)), 2),
                "ATR": round(float(row.get("ATR", 0)), 2)
            })

    return pd.DataFrame(rows)

# ───────── main ─────────
if __name__ == "__main__":
    fetch_start = "2020-01-01"
    fetch_end   = datetime.today().strftime("%Y-%m-%d")

    results = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as exe:
        futs = {exe.submit(scan_symbol, s, fetch_start, fetch_end): s for s in SYMBOLS}
        for fut in as_completed(futs):
            df = fut.result()
            if df is not None and not df.empty:
                results.append(df)

    if results:
        out = pd.concat(results, ignore_index=True)
        if PRINT_FROM:
            out = out[pd.to_datetime(out["Date"]) >= pd.to_datetime(PRINT_FROM)]
        if PRINT_TO:
            out = out[pd.to_datetime(out["Date"]) <= pd.to_datetime(PRINT_TO)]
        out = out.sort_values(["Date","Ticker"], ascending=[False, True])
        pd.set_option("display.max_columns", None, "display.width", 0)
        print(f"\nMomentum D3 Extended Pattern — trade-day hits:\n")
        print(out.to_string(index=False))
    else:
        print("No hits found. Consider adjusting parameters.")

# Usage Instructions:
# 1. Adjust parameters in the ScannerConfig class above
# 2. Run the scanner normally
# 3. 31 parameters are now user-configurable
