const testCode = `"""
EdgeDev V31 Trading Scanner
Generated by Renata Multi-Agent System
2026-01-06T15:06:06.316Z
"""

import mcal
import mcal
import mcal
from typing import List, Dict, Any

class ScannerConfig:
    min_price = 10
`;

function ensureV31Compliance(code) {
  const requiredImports = [
    'import pandas as pd',
    'import numpy as np',
    'import mcal',
    'from typing import List, Dict, Any'
  ];

  const lines = code.split('\n');
  const importLines = {};
  const nonImportLines = [];
  let importSectionEnd = 0;

  lines.forEach((line, index) => {
    const trimmedLine = line.trim();

    if (requiredImports.some(imp => trimmedLine === imp || trimmedLine.startsWith(imp))) {
      const baseImport = requiredImports.find(imp => trimmedLine === imp || trimmedLine.startsWith(imp));
      if (baseImport) {
        importLines[baseImport] = index;
      }
      importSectionEnd = index + 1;
    } else if (trimmedLine.startsWith('import ') || trimmedLine.startsWith('from ')) {
      importSectionEnd = index + 1;
    } else {
      nonImportLines.push(line);
    }
  });

  const compliantImports = [];

  // Add docstring if present at start
  let docStartIndex = 0;
  if (nonImportLines.length > 0 && nonImportLines[0].trim().startsWith('"""')) {
    const docEndIndex = nonImportLines.findIndex((line, i) => i > 0 && line.trim().startsWith('"""'));
    if (docEndIndex !== -1) {
      const docstring = nonImportLines.slice(0, docEndIndex + 1).join('\n');
      compliantImports.push(docstring);
      docStartIndex = docEndIndex + 1;
    }
  }

  // Add all required imports in exact order (no duplicates!)
  requiredImports.forEach(imp => {
    compliantImports.push(imp);
  });

  // Combine: imports + rest of code (after docstring)
  const remainingCode = nonImportLines.slice(docStartIndex).join('\n');

  return [...compliantImports, remainingCode].join('\n');
}

const result = ensureV31Compliance(testCode);
console.log('=== RESULT ===');
console.log(result);
